global nl.jads.sodalite.rules.RefactoringManager refMgt;
global nl.jads.sodalite.rules.DisabledRuleSet disabledSet;
import nl.jads.sodalite.events.LocationChangedEvent;
import nl.jads.sodalite.events.DeploymentNeeded;
import nl.jads.sodalite.events.DeploymentChanged;
import nl.jads.sodalite.events.DeploymentRemove;
import nl.jads.sodalite.events.Alert
import java.util.Arrays

rule "de_to_it"
  when
    $f1 : LocationChangedEvent(preLoc == "de", currentLoc == "it") and
    $f2 : DeploymentChanged()
  then
    disabledSet.disable("de_to_it");
    System.out.println("de_to_it rule triggered");
    refMgt.undeployDeploymentModel($f1.getPreLoc());
    refMgt.deployDeploymentModel($f1.getCurrentLoc());
    System.out.println("de_to_it rule executed");
end

rule "deploy_it"
  when
    $f1 : DeploymentNeeded(currentLoc == "it")
  then
    disabledSet.disable("deploy_it");
    System.out.println("deploy_it rule triggered");
    refMgt.deployDeploymentModel($f1.getCurrentLoc());
    System.out.println("deploy_it rule executed");
end

rule "deploy_at"
  when
    $f1 : DeploymentNeeded(currentLoc == "at")
  then
    disabledSet.disable("deploy_at");
    System.out.println("deploy_at rule triggered");
    refMgt.deployDeploymentModel($f1.getCurrentLoc());
    System.out.println("deploy_at rule executed");
end

rule "deploy_remove_at"
  when
    $f1 : DeploymentRemove(preLoc == "at")
  then
    disabledSet.disable("deploy_remove_at");
    System.out.println("deploy_remove_at rule triggered");
    refMgt.undeployDeploymentModel($f1.getPreLoc());
    System.out.println("deploy_remove_at rule executed");
end

rule "deploy_remove_it"
  when
    $f1 : DeploymentRemove(preLoc == "it")
  then
    disabledSet.disable("deploy_remove_it");
    System.out.println("deploy_remove_it rule triggered");
    refMgt.undeployDeploymentModel($f1.getPreLoc());
    System.out.println("deploy_remove_it rule executed");
end

rule "HostHighCpuLoad"
  when
    $f1 : Alert(name == "HostHighCpuLoad", variant=="vehicle-iot-demo-v1")
  then
    disabledSet.disable("HostHighCpuLoad");
    System.out.println("HostHighCpuLoad rule triggered");
//    refMgt.unDeploy("");
//    refMgt.deploy("");
    System.out.println("HostHighCpuLoad rule executed");
end

rule "HostLowCpuLoad"
  when
    $f1 : Alert(name == "HostLowCpuLoad", variant=="vehicle-iot-demo-v2")
  then
    disabledSet.disable("HostLowCpuLoad");
    System.out.println("HostLowCpuLoad rule triggered");
//    refMgt.unDeploy("");
//    refMgt.deploy("");
    System.out.println("HostLowCpuLoad rule executed");
end