apiVersion: apps/v1
kind: Deployment
metadata:
  name: skydive-prometheus-connector
spec:
  replicas: 1
  selector:
    matchLabels:
      app: skydive-prometheus-connector
  template:
    metadata:
      labels:
        app: skydive-prometheus-connector
    spec:
      containers:
      - env:
        - name: SKYDIVE_ANALYZERS
          value: 35.242.242.25:32505
        - name: SKYDIVE_LOGGING_LEVEL
          value: INFO
        - name: SKYDIVE_PIPELINE_SUBSCRIBER_URL
          value: ws://35.242.242.25:32505/ws/subscriber/flow
        - name: SKYDIVE_PIPELINE_MANGLE
          value: none
        - name: SKYDIVE_PIPELINE_TRANSFORM_TYPE
          value: none
        - name: SKYDIVE_PIPELINE_STORE_TYPE
          value: prom_sky_con
        - name: SKYDIVE_PIPELINE_STORE_PROM_SKY_CON_PORT
          value: '9100'
        image: sodaliteh2020/prometheus-skydive-connector:2
        imagePullPolicy: Always
        name: skydive-prometheus-connector
        ports:
        - containerPort: 9100
          protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: skydive-prometheus-connector
  name: skydive-prometheus-connector
spec:
  ports:
  - name: api
    nodePort: 32222
    port: 9100
    protocol: TCP
    targetPort: 9100
  selector:
    app: skydive-prometheus-connector
  sessionAffinity: None
  type: NodePort
