global nl.jads.sodalite.rules.RefactoringManager refMgt;
global nl.jads.sodalite.rules.DisabledRuleSet disabledSet;
import nl.jads.sodalite.events.Alert
import java.util.Arrays
import nl.jads.sodalite.dto.AADMModel
import tosca.mapper.dto.Node
import tosca.mapper.dto.Property
import nl.jads.sodalite.events.ResourceEvent;

rule "KBUpdated"
  when
    $f1 : ResourceEvent(eType == "KBUpdated", rType=="any")
  then
    disabledSet.disable("KBUpdated");
    ResourceEvent newREvent = new ResourceEvent();
    newREvent.setrType("gpu");
    Node nodeGPU = refMgt.findMatchingNode(
                        "( ?name = \"xavier-nx\" ) && ( ?gpus = " + 1 + " ) && ( ?cpus = " + 1 + " )" + " && ( ?ready_status = " + true + " )",
                        "https://www.sodalite.eu/ontologies/workspace/1/6inp70u8k18dpf8gda7g3n3lv5/AADM_c2sm3t0eon1fivdpnsj41f6b6k");
    if (nodeGPU != null) {
           newREvent.seteType("ResourceAdded");
           newREvent.setNode(nodeGPU);
    } else {
           newREvent.seteType("ResourceRemoved");
    }
    retract($f1);
    insert(newREvent);
    System.out.println("KBUpdated rule executed");
end

rule "GPUUnavailable"
  when
    $f1 : ResourceEvent(eType == "ResourceRemoved", rType=="gpu")
  then
    disabledSet.disable("GPUUnavailable");
    AADMModel aadmModel = refMgt.getAadm();
    aadmModel.updateNestedParameterOfProperty("knowgo-score-helm", "values", "accelerators",
                       "gpu", "false");
    refMgt.saveAndUpdate();
    System.out.println("GPU Unavailable rule executed");
end

rule "GPUAvailable"
  when
    $f1 : ResourceEvent(eType == "ResourceAdded", rType=="gpu")
  then
    disabledSet.disable("GPUAvailable");
    AADMModel aadmModel = refMgt.getAadm();
    aadmModel.updateNestedParameterOfProperty("knowgo-score-helm", "values", "accelerators",
                         "gpu", "true");
    refMgt.saveAndUpdate();
    System.out.println("GPU available rule executed");
end