---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: chaos-monitor
  name: chaos-monitor
spec:
  replicas: 1
  selector:
    matchLabels:
      app: chaos-monitor
  template:
    metadata:
      labels:
        app: chaos-monitor
    spec:
      containers:
      - image: shubh214/chaos-exporter:ci
        imagePullPolicy: Always
        name: chaos-exporter
        env:
        - name: WATCH_NAMESPACE
          value: 'default'
        - name: TSDB_SCRAPE_INTERVAL
          value: '1s'
        - name : INJECTION_TIME_FILTER
          value: "disable"
      serviceAccountName: litmus
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: chaos-monitor
  name: chaos-monitor
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
    nodePort: 31111
  selector:
    app: chaos-monitor
  type: NodePort
